apiVersion: v1
kind: ServiceList
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: nsolid-registry
    spec:
      ports:
        - port: 4001
          targetPort: clientport
      selector:
        app: nsolid-registry
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: nsolid-proxy
    spec:
      sessionAffinity: None
      ports:
        - port: 9000
          targetPort: proxy
      selector:
        app: nsolid-proxy
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: nsolid-console
    spec:
      sessionAffinity: ClientIP
      type: LoadBalancer
      ports:
        - port: 80
          targetPort: console
      selector:
        app: nsolid-console
