apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsolid-deployment
  labels:
    app: nsolid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsolid
  template:
    metadata:
      labels:
        app: nsolid
    spec:
      containers:
        - name: nsolid
          imagePullPolicy: Always
          image: 800406105498.dkr.ecr.us-west-2.amazonaws.com/kubernetes/test:latest
          ports:
            - containerPort: 3000
          env:
            - name: NSOLID_APPNAME
              value: "Sample App"
            - name: NSOLID_TAGS
              value: "production,nextjs,nsolid-hydrogen"
            # - name: NSOLID_SAAS
            #   valueFrom:
            #     secretKeyRef:
            #       name: nsolid-saas-secret
            #       key: nsolid_saas
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            privileged: true
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: artifacts-volume
              mountPath: /artifacts
            - name: html-output-volume
              mountPath: /html_output
          command: ["0x", "--kernel-tracing", "--output-dir", "/artifacts/{pid}.0x", "--output-html", "/html_output/{name}.html", "--", "node", "server.js"]
      terminationGracePeriodSeconds: 30
      volumes:
        - name: artifacts-volume
          persistentVolumeClaim:
            claimName: artifacts-pvc
        - name: html-output-volume
          persistentVolumeClaim:
            claimName: html-output-pvc
