apiVersion: v1
kind: Secret
metadata:
  name: nsolid-saas-secret
  namespace: default
type: Opaque
data:
  # Base64 encoded value for nsolid_saas (e.g., echo -n "your-secret" | base64)
  nsolid_saas: <base64-encoded-value>
