apiVersion: extensions/v1beta1
kind: DeploymentList
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      labels:
        app: nsolid-registry
      name: nsolid-registry
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: nsolid-registry
        spec:
          containers:
          - image: nodesource/nsolid-registry
            name: nsolid-registry
            ports:
            - containerPort: 2380
              name: serverport
            - containerPort: 2379
              name: clientport
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      name: nsolid-console
      labels:
        app: nsolid-console
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: nsolid-console
        spec:
          containers:
            - name: console
              image: "nodesource/nsolid-console:v1.7.3"
              env:
                - name: NSOLID_HUB
                  value: "nsolid-registry:2379"
              args:
                - --hub=http://nsolid-proxy:9000
              ports:
                - containerPort: 3000
                  name: console
                - containerPort: 8000
                  name: nsolid
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      name: nsolid-proxy
      labels:
        app: nsolid-proxy
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: nsolid-proxy
        spec:
          containers:
            - name: proxy
              image: "nodesource/nsolid-hub:v4.0.0"
              args:
                - --registry=nsolid-registry:2379
              env:
                - name: NSOLID_APPNAME
                  value: nsolid-proxy
                - name: NSOLID_HUB
                  value: "nsolid-registry:2379"
                - name: NSOLID_SOCKET
                  value: "8000"
                - name: NSOLID_TAGS
                  value: "nsolid-v1.4.0,proxy-v4.0.0"
              ports:
                - containerPort: 9000
                  name: proxy
                - containerPort: 8000
                  name: nsolid
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      labels:
        app: nsolid-secure-proxy
      name: nsolid-secure-proxy
    spec:
      replicas: 2
      template:
        metadata:
          labels:
            app: nsolid-secure-proxy
        spec:
          containers:
          - image: nginx
            imagePullPolicy: Always
            name: nsolid-secure-proxy
            ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            volumeMounts:
            - mountPath: /etc/nginx/
              name: nginx-config
            - mountPath: /etc/nginx/ssl/
              name: nginx-tls
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 30
              timeoutSeconds: 1
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 1
          restartPolicy: Always
          volumes:
          - name: nginx-tls
            secret:
              secretName: nginx-tls
          - name: nginx-config
            configMap:
              name: nginx-config