apiVersion: v1
kind: ServiceList
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: registry
    spec:
      ports:
        - port: 80
          targetPort: clientport
      selector:
        app: registry
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: hub
    spec:
      sessionAffinity: None
      ports:
        - port: 80
          targetPort: hub
      selector:
        app: hub
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: console
    spec:
      sessionAffinity: ClientIP
      ports:
        - port: 80
          targetPort: console
      selector:
        app: console
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: nsolid
      name: nginx-secure-proxy
      labels:
        app: nginx-secure-proxy
    spec:
      type: LoadBalancer
      sessionAffinity: ClientIP
      ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 80
        - name: https
          protocol: TCP
          port: 443
          targetPort: 443
      selector:
        app: nginx-secure-proxy
