apiVersion: v1
kind: PersistentVolumeClaimList
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      namespace: nsolid
      name: nsolid-registry
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      namespace: nsolid
      name: nsolid-console
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: DeploymentList
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      labels:
        app: registry
      name: registry
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: registry
        spec:
          containers:
          - image: nodesource/nsolid-registry
            name: registry
            args:
              - "--data-dir"
              - /var/lib/nsolid/registry
            ports:
            - containerPort: 2380
              name: serverport
            - containerPort: 2379
              name: clientport
            volumeMounts:
            - name: nsolid-registry
              mountPath: /var/lib/nsolid/registry
          volumes:
          - name: nsolid-registry
            persistentVolumeClaim:
              claimName: nsolid-registry
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      name: console
      labels:
        app: console
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: console
        spec:
          containers:
            - name: console
              image: "nodesource/nsolid-console:v1.7.3"
              args:
                - --hub=http://hub:80
                - --storage=/var/lib/nsolid/console
              ports:
                - containerPort: 3000
                  name: console
                - containerPort: 8000
                  name: nsolid
              volumeMounts:
              - name: nsolid-console
                mountPath: /var/lib/nsolid/console
          volumes:
          - name: nsolid-console
            persistentVolumeClaim:
              claimName: nsolid-console
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      name: hub
      labels:
        app: hub
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: hub
        spec:
          containers:
            - name: hub
              image: "nodesource/nsolid-hub:v4.0.0"
              args:
                - --registry=registry:80
              ports:
                - containerPort: 9000
                  name: hub
                - containerPort: 8000
                  name: nsolid
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      namespace: nsolid
      labels:
        app: nginx-secure-proxy
      name: nginx-secure-proxy
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: nginx-secure-proxy
        spec:
          containers:
          - image: nginx
            imagePullPolicy: Always
            name: nginx-secure-proxy
            ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            volumeMounts:
            - mountPath: /etc/nginx/
              name: nginx-config
            - mountPath: /etc/nginx/ssl/
              name: nginx-tls
            livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 30
              timeoutSeconds: 1
            readinessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 1
          restartPolicy: Always
          volumes:
          - name: nginx-tls
            secret:
              secretName: nginx-tls
          - name: nginx-config
            configMap:
              name: nginx-config
